delta_kinematics:
  ros__parameters:
    base_triangle_side_length: 346.41016151377545 # [mm] (r_base=100 mm, SB = 2 * r_base * sqrt(3))
    end_effector_side_length: 112.58330249197702 # [mm] (r_ee=32.5 mm, SP = 2 * r_ee * sqrt(3))
    active_link_length: 100.0 # [mm]
    passive_link_length: 200.0 # [mm]
    passive_link_width: 42.84670 # [mm]
    joint_min: -0.174532925199 # [rad] (-10 deg)
    joint_max: 1.57079632679 # [rad] (90 deg)
    max_joint_velocity: 11.1 # [rad/s] (106 RPM as requested)
    robot_config_freq: 50.0 # [Hz]  

motion_planner:
  ros__parameters:
    commanded_tf_parent_frame: delta_robot/world_link
    commanded_tf_child_frame: delta_robot/commanded_end_effector_pin
    calculated_fk_tf_parent_frame: delta_robot/world_link
    calculated_fk_tf_child_frame: delta_robot/calculated_fk_end_effector_pin
    actual_fk_tf_parent_frame: delta_robot/world_link
    actual_fk_tf_child_frame: delta_robot/actual_fk_end_effector_pin
    ee_to_tilt_axis_offset_m: -0.027625
    tilt_axis_to_tool_tip_offset_m: -0.0225
    tool_tip_to_object_center_offset_m: 0.0
    enable_tilt_axis_compensation: true